### ISSUE TITLE
Typo: trakes -> takes

### ISSUE THREAD

**Issue by claremacrae** [mProjectsCode/obsidian-stats#12]
Sorry to be submitting an issue instead of a PR - I spent a good while forking, searching, trying to edit the source file on the GitHub Web UI and gave up...

<img width="740" alt="image" src="https://github.com/user-attachments/assets/784a2fdd-dc7c-4812-8957-46eb689f91a0">

**Comment by mProjectsCode** [comment]
Thanks :)

The corresponding source code line would be [here](https://github.com/mProjectsCode/obsidian-stats/blob/094434ebc584b4d0b0619161b4847d8c524c88c5/website/src/components/plugin.astro#L149), but I have already fixed it in my clone of the repo. It will be in the next update once I finish the other stuff that I am working on

**Comment by claremacrae** [comment]
Yeah, the GitHub Web UI struggled to edit that file, at least on Safari on Mac...

Thanks.
