### ISSUE TITLE
[BUG] Version History contains deleted versions

### ISSUE THREAD

**Issue by 4Source** [mProjectsCode/obsidian-stats#6]
First of all, really good job you did. 

I recently discovered that version history also contains deleted versions. This is a problem for my plugin and I could imagine for others too. If you use pre-release versions that only exist in a non-main branch for testing, I delete them after the release. Possible solutions would be to overwrite the release dates from time to time with newly fetched releases. Another option would be to check whether the version you are pulling is a pre-release version. If so, don't include them in the history. This would be a good idea anyway since Obsidian doesn't support them.

**Comment by mProjectsCode** [comment]
The release data is based on the data that obsidian collects on downloads of releases. So please direct your feedback at the obsidian releases repo.

**Comment by 4Source** [comment]
Ok, that's interesting, but ok, thanks for your quick answer.
