### ISSUE TITLE
Not possible to run

### ISSUE THREAD

**Issue by 4Source** [mProjectsCode/obsidian-stats#7]
```
bun run index.ts
```

Didn't work 

```
D:\Documents\Projekte\Aktuell\obsidian-stats>bun --version
1.0.30

D:\Documents\Projekte\Aktuell\obsidian-stats>bun run index.ts
error: Script not found "index.ts"
```

**Comment by mProjectsCode** [comment]
> Script not found "index.ts"

Because there is no `index.ts`.

**Comment by mProjectsCode** [comment]
if you want to update the data, look at the root `package.json` and it's scripts. If you want to start the website, look at `website/package.json` (`cd website && bun run dev` to start the dev server and `cd website && bun run build` to make a prod build of the website).
