### ISSUE TITLE
Duplicate `Most Downloaded New Plugins of 2023` headings

### ISSUE THREAD

**Issue by claremacrae** [mProjectsCode/obsidian-stats#9]
https://www.moritzjung.dev/obsidian-stats/pluginstats/hall-of-fame/#2024

<img src="https://github.com/user-attachments/assets/0ade6884-477e-4fe5-8c4f-afe3ccfa82cf" width="400">

**Comment by claremacrae** [comment]
Oops - I hit return and saved it before finishing editing.

It looks like the first line:

`Most Downloaded New Plugins of 2023`

Should be one of:

`Most Downloaded New Plugins of 2024`
`Most Downloaded New Plugins of 2024 (Preliminary)`

**Comment by mProjectsCode** [comment]
Oh yeah, it seems like i did a bad copy paste job XD.

Thanks for the report.

**Comment by mProjectsCode** [comment]
Should be fixed
